# Generated by Django 3.2.7 on 2021-10-13 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_auto_20210923_1333'),
        ('events', '0002_auto_20211007_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AddField(
            model_name='event',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='events_event', serialize=False, to='cms.cmsplugin'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EventPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='events_eventplugin', serialize=False, to='cms.cmsplugin')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugins', to='events.event')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
