# Generated by Django 3.2.7 on 2021-12-14 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0023_auto_20210923_1333'),
        ('core', '0006_tooldetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_cms_integration_toolpluginmodel', serialize=False, to='cms.cmsplugin')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tooldetail')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
