# Generated by Django 3.2.7 on 2021-10-21 07:14

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0023_auto_20210923_1333'),
        ('core', '0002_auto_20211021_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='core_tool', serialize=False, to='cms.cmsplugin')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('feature_image', models.ImageField(upload_to=core.models.upload_tool_image)),
                ('year_developed', models.DateField()),
                ('description', models.TextField(help_text='e.g. An overview of the tool', null=True)),
                ('link', models.URLField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Analytical Tools',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
