# Generated by Django 3.2.7 on 2021-11-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.DeleteModel(
            name='ToolKit',
        ),
    ]
