# Generated by Django 3.2.7 on 2021-12-14 12:03

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_alter_tool_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('feature_image', models.ImageField(upload_to=core.models.upload_tool_image)),
                ('year_developed', models.DateField()),
                ('description', models.TextField(help_text='e.g. An overview of the tool', null=True)),
                ('link', models.URLField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Analytical Tools',
            },
        ),
    ]
