"""
Django settings for geo_ldn project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from os import environ, path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
PROJECT_DIR = path.dirname(path.dirname(path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = environ.get("SECRET_KEY", "#e@7sv9=!^h-c+vn")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = environ.get("ENV", "development") == "development"
TEMPLATE_DEBUG = DEBUG

ALLOWED_HOSTS = environ.get("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

# Application definition
DJANGO_APPS = [
    "django.contrib.humanize",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "django.contrib.gis",
]

WAGTAIL_APPS = [
    "wagtail.contrib.modeladmin",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    "taggit",
]

INSTALLED_APPS = ["pages.blog", "pages.home"] + WAGTAIL_APPS + DJANGO_APPS

if DEBUG:
    # INSTALLED_APPS += ["debug_toolbar"]

    INTERNAL_IPS = ["127.0.0.1"]

MIDDLEWARE = [
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# if DEBUG:
#     MIDDLEWARE += ["debug_toolbar.middleware.DebugToolbarMiddleware"]

ROOT_URLCONF = "app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [path.join(PROJECT_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "app.wsgi.application"

CSRF_TRUSTED_ORIGINS = ["https://*.zisake.io", "https://*.127.0.0.1"]

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": "geo_ldn_db",
        "USER": "postgres",
        "PASSWORD": "p0stgr3s",
        "HOST": "127.0.0.1",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 9,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Nairobi" if DEBUG else "Europe/Berlin"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"
STATICFILES_DIRS = [path.join(PROJECT_DIR, "dist"), path.join(PROJECT_DIR, "static")]
STATIC_ROOT = path.join(PROJECT_DIR, "public")
STATIC_URL = "/public/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Media files uploaded by user (images / videos)
MEDIA_ROOT = path.join(PROJECT_DIR, "uploads")
MEDIA_URL = "/uploads/"

# Wagtail settings
WAGTAIL_SITE_NAME = "GEO Land Degradation Neutrality Flagship (GEO-LDN)"
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}
WAGTAILADMIN_BASE_URL = environ.get("BASE_URL", "http://127.0.0.1:8000")
WAGTAIL_APPEND_SLASH = True
WAGTAILADMIN_RECENT_EDITS_LIMIT = 5
WAGTAIL_AUTO_UPDATE_PREVIEW_INTERVAL = 2000
WAGTAILADMIN_UNSAFE_PAGE_DELETION_LIMIT = 3
WAGTAIL_USER_TIME_ZONES = [
    "Australia/Sydney",
    "Asia/Tokyo",
    "Africa/Nairobi",
    "Europe/Berlin",
    "America/Chicago",
]
WAGTAIL_DATE_FORMAT = "%M %d, %Y"
WAGTAIL_DATETIME_FORMAT = "%M %d, %Y at %h:%i %a"
WAGTAIL_TIME_FORMAT = "%h:%i %A"
WAGTAILADMIN_NOTIFICATION_FROM_EMAIL = environ.get("EMAIL_ADDRESS", "test@test.com")
WAGTAILADMIN_NOTIFICATION_INCLUDE_SUPERUSERS = DEBUG
WAGTAIL_ENABLE_WHATS_NEW_BANNER = DEBUG
WAGTAILAPI_SEARCH_ENABLED = DEBUG != False
WAGTAILAPI_USE_FRONTENDCACHE = DEBUG
WAGTAILADMIN_RICH_TEXT_EDITORS = {
    "default": {
        "WIDGET": "wagtail.admin.rich_text.DraftailRichTextArea",
        "OPTIONS": {
            "features": [
                "h1",
                "h2",
                "h3",
                "h4",
                "bold",
                "italic",
                "link",
                "document-link",
                "image",
                "embed",
                "superscript",
                "subscript",
                "strikethrough",
                "blockquote",
                "ol",
                "ul",
            ]
        },
    },
    "secondary": {
        "WIDGET": "some.external.RichTextEditor",
    },
}

# setup frontend caching of wagtail
if (
    environ.get("CLOUDFLARE_API_KEY") is not None
    and environ.get("CLOUDFLARE_ZONE_ID") is not None
    and environ.get("CLOUDFLARE_EMAIL_ADDRESS") is not None
):
    WAGTAILFRONTENDCACHE = {
        "cloudflare": {
            "BACKEND": "wagtail.contrib.frontend_cache.backends.CloudflareBackend",
            "EMAIL": environ.get("CLOUDFLARE_EMAIL_ADDRESS"),
            "API_KEY": environ.get("CLOUDFLARE_API_KEY"),
            "ZONEID": environ.get("CLOUDFLARE_ZONE_ID"),
        },
    }

# taggit settings
TAG_LIMIT = 7

# Admins settings
SERVER_EMAIL = environ.get("EMAIL_ADDRESS", "test@test.com")
ADMIN = [
    ("zisake.io", "hello@zisake.io"),
    ("GEO LDN", environ.get("EMAIL_ADDRESS", "test@test.com")),
]

# Cache framework settings
if environ.get("REDIS_URL") is not None:
    # ensure to create database cache table i.e [$ python manage.py createcachetable]
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": environ.get("REDIS_URL", "redis://localhost:6379"),
        }
    }

# Web security settings
X_FRAME_OPTIONS = "SAMEORIGIN"

# smtp settings
if not DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = environ.get("SMTP_HOST")
    EMAIL_PORT = environ.get("SMTP_PORT")
    EMAIL_HOST_PASSWORD = environ.get("SMTP_PASSWORD")
    EMAIL_HOST_USER = environ.get("SMTP_USERNAME")

    if environ.get("SMTP_AUTH") == "ssl":
        EMAIL_USE_SSL = True
    else:
        EMAIL_USE_TLS = True

else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    # EMAIL_FILE_PATH = "/tmp/geo-ldn.org/email-messages"

# site settings
SITE_ID = 1
