# Generated by Django 3.2.7 on 2021-12-14 12:03

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='article-default.jpg', upload_to=blog.models.upload_article_image),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category-default.jpg', upload_to=blog.models.upload_category_image),
        ),
    ]
