# Generated by Django 4.2.2 on 2023-07-03 13:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="date",
            field=models.DateField(null=True, verbose_name="Post date"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="feed_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
