# Generated by Django 4.2.2 on 2023-07-03 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_homepage_body_homepage_date_homepage_feed_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="date",
        ),
    ]
