# Generated by Django 4.2.2 on 2023-07-03 21:03

from django.db import migrations
import django.utils.timezone
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_remove_homepage_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="feed_image",
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_section",
            field=wagtail.fields.StreamField(
                [
                    ("title", wagtail.blocks.TextBlock(null=True)),
                    ("subtitle", wagtail.blocks.TextBlock(null=True)),
                    ("about_text", wagtail.blocks.RichTextBlock(null=True)),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="carousel",
            field=wagtail.fields.StreamField(
                [
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    (
                        "heading",
                        wagtail.blocks.TextBlock(
                            blank=True, max_length=100, required=True, rows=2
                        ),
                    ),
                    (
                        "caption",
                        wagtail.blocks.TextBlock(
                            blank=True, max_length=255, required=True, rows=4
                        ),
                    ),
                ],
                default=django.utils.timezone.now,
                use_json_field=True,
            ),
            preserve_default=False,
        ),
    ]
