# Generated by Django 4.2.2 on 2023-07-03 21:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_remove_homepage_about_section"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="carousel",
        ),
    ]
