# Generated by Django 4.2.2 on 2023-07-03 21:09

from django.db import migrations
import django.utils.timezone
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_remove_homepage_carousel"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="about_section",
            field=wagtail.fields.StreamField(
                [
                    ("title", wagtail.blocks.TextBlock(required=True, rows=2)),
                    ("subtitle", wagtail.blocks.TextBlock(required=True, rows=2)),
                    ("about_text", wagtail.blocks.RichTextBlock(required=True)),
                ],
                default=django.utils.timezone.now,
                use_json_field=True,
            ),
            preserve_default=False,
        ),
    ]
