# Generated by Django 4.2.2 on 2023-07-03 21:10

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_alter_homepage_about_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="about_section",
            field=wagtail.fields.StreamField(
                [
                    ("title", wagtail.blocks.TextBlock()),
                    ("subtitle", wagtail.blocks.TextBlock()),
                    ("about_text", wagtail.blocks.RichTextBlock()),
                ],
                use_json_field=True,
            ),
        ),
    ]
