# Generated by Django 4.2.2 on 2023-07-03 21:18

from django.db import migrations
import django.utils.timezone
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_alter_homepage_about_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="carousel",
            field=wagtail.fields.StreamField(
                [
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    (
                        "heading",
                        wagtail.blocks.TextBlock(max_length=100, required=True, rows=2),
                    ),
                    (
                        "caption",
                        wagtail.blocks.TextBlock(max_length=255, required=True, rows=4),
                    ),
                ],
                default=django.utils.timezone.now,
                use_json_field=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="homepage",
            name="about_section",
            field=wagtail.fields.StreamField(
                [
                    (
                        "title",
                        wagtail.blocks.TextBlock(
                            help_text="Title of the about section",
                            required=True,
                            rows=2,
                        ),
                    ),
                    (
                        "subtitle",
                        wagtail.blocks.TextBlock(
                            help_text="Subtitle of the about section",
                            required=True,
                            rows=4,
                        ),
                    ),
                    (
                        "content",
                        wagtail.blocks.RichTextBlock(
                            help_text="Actual content", required=True
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
