# Generated by Django 4.2.2 on 2023-07-03 21:25

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_remove_homepage_carousel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="about_section",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="title")),
                    ("sub_heading", wagtail.blocks.CharBlock()),
                    ("content", wagtail.blocks.RichTextBlock()),
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                ],
                use_json_field=True,
            ),
        ),
    ]
