# Generated by Django 4.2.2 on 2023-07-03 21:31

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_homepage_carousel_alter_homepage_about_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="about_section",
            field=wagtail.fields.StreamField(
                [
                    ("title", wagtail.blocks.TextBlock(required=True, rows=2)),
                    ("subtitle", wagtail.blocks.TextBlock(required=True, rows=2)),
                    ("about_text", wagtail.blocks.RichTextBlock(required=True)),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="carousel",
            field=wagtail.fields.StreamField(
                [
                    ("image", wagtail.images.blocks.ImageChooserBlock()),
                    (
                        "heading",
                        wagtail.blocks.TextBlock(max_length=100, required=True, rows=2),
                    ),
                    (
                        "caption",
                        wagtail.blocks.TextBlock(max_length=255, required=True, rows=4),
                    ),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
