# Generated by Django 4.2.2 on 2023-07-03 21:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_alter_homepage_about_section_alter_homepage_carousel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="about_section",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="carousel",
        ),
    ]
