# Generated by Django 4.2.2 on 2023-07-03 21:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("home", "0016_remove_homepage_about_section_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="body",
        ),
        migrations.AddField(
            model_name="homepage",
            name="about_section",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.TextBlock()),
                    ("subheading", wagtail.blocks.TextBlock()),
                    ("content", wagtail.blocks.RichTextBlock()),
                ],
                default=django.utils.timezone.now,
                use_json_field=True,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="HomePageCarousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("heading", models.CharField(max_length=125)),
                ("paragraph", models.TextField(max_length=255)),
                (
                    "image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carousel_images",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
