# Generated by Django 4.2.2 on 2023-07-03 21:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0017_remove_homepage_body_homepage_about_section_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="about_section",
        ),
    ]
