# Generated by Django 4.2.2 on 2023-07-03 21:59

from django.db import migrations
import django.utils.timezone
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0018_remove_homepage_about_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="about_section",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.TextBlock()),
                    ("subheading", wagtail.blocks.TextBlock()),
                    ("content", wagtail.blocks.RichTextBlock()),
                ],
                default=django.utils.timezone.now,
                use_json_field=True,
            ),
            preserve_default=False,
        ),
    ]
