# Generated by Django 4.2.2 on 2023-07-03 22:01

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0019_homepage_about_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="about_section",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.TextBlock()),
                    ("subheading", wagtail.blocks.TextBlock()),
                    ("content", wagtail.blocks.RichTextBlock()),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
