# Generated by Django 4.2.2 on 2023-07-03 22:15

from django.db import migrations
import django.utils.timezone
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0020_alter_homepage_about_section"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="about_section",
        ),
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock(form_classname="title")),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                ],
                default=django.utils.timezone.now,
                use_json_field=True,
            ),
            preserve_default=False,
        ),
    ]
