# Generated by Django 4.2.2 on 2023-07-03 22:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0022_remove_homepage_body_homepage_about_section"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="about_section",
        ),
    ]
