# Generated by Django 4.2.2 on 2023-07-03 22:28

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0024_homepage_about_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="about_section",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.CharBlock(
                            default="About section",
                            form_classname="title",
                            max_length=125,
                            null=True,
                        ),
                    ),
                    (
                        "sub_heading",
                        wagtail.blocks.CharBlock(
                            default="About section",
                            form_classname="subtitle",
                            max_length=255,
                            null=True,
                        ),
                    ),
                    ("content", wagtail.blocks.RichTextBlock(blank=True)),
                ],
                default=None,
                use_json_field=True,
            ),
        ),
    ]
