# Generated by Django 4.2.2 on 2023-07-05 06:42

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0027_alter_homepage_about_section"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={
                "permissions": [("can_change_page_level", "Can change the page level")],
                "verbose_name": "GEO-LDN Home page",
                "verbose_name_plural": "GEO-LDN Home pages",
            },
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="about_section",
        ),
        migrations.RemoveField(
            model_name="homepagecarousel",
            name="paragraph",
        ),
        migrations.AddField(
            model_name="homepage",
            name="page_level",
            field=models.CharField(
                choices=[("Root Page", "L1"), ("Main Page", "L2"), ("Blog Page", "L3")],
                default="L1",
            ),
        ),
        migrations.AddField(
            model_name="homepagecarousel",
            name="subheading",
            field=models.CharField(
                default="GEO-LDN is a stakeholder-driven initiative that aims to boost co-operation between Earth observation data providers and Governments.",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="homepagecarousel",
            name="heading",
            field=models.CharField(
                default="Land Degradation Neutrality Initiative", max_length=125
            ),
        ),
        migrations.CreateModel(
            name="HomePageAboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "image",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "caption",
                                            wagtail.blocks.CharBlock(required=True),
                                        ),
                                        (
                                            "image",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                required=True
                                            ),
                                        ),
                                    ]
                                ),
                            ),
                            (
                                "heading",
                                wagtail.blocks.CharBlock(
                                    default="GEO-LDN FLAGSHIP",
                                    form_classname="title",
                                    max_length=70,
                                    required=True,
                                ),
                            ),
                            (
                                "section_content",
                                wagtail.blocks.RichTextBlock(
                                    help_text="A brief piece of information about the corporation",
                                    required=True,
                                ),
                            ),
                            (
                                "subheading",
                                wagtail.blocks.CharBlock(
                                    default="Enhancing co-operation between Earth observation data providers and Governments.",
                                    form_classname="subtitle",
                                    max_length=100,
                                    required=False,
                                ),
                            ),
                        ],
                        use_json_field=True,
                    ),
                ),
                (
                    "video_link",
                    models.URLField(
                        blank=True,
                        help_text="Please provide a YouTube embed link",
                        unique=True,
                    ),
                ),
                (
                    "video_caption",
                    models.CharField(
                        default="Land Degradation Neutrality Initiative", max_length=125
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="about_section",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
