# Generated by Django 4.2.2 on 2023-07-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0028_alter_homepage_options_remove_homepage_about_section_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagecarousel",
            name="subheading",
            field=models.CharField(
                default="GEO-LDN is a stakeholder-driven initiative that aims to boost co-operation between Earth observation data providers and Governments.",
                max_length=150,
            ),
        ),
    ]
