# Generated by Django 4.2.2 on 2023-07-05 07:03

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0029_alter_homepagecarousel_subheading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepageaboutsection",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                ("caption", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=True
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "heading",
                        wagtail.blocks.CharBlock(
                            default="GEO-LDN FLAGSHIP",
                            form_classname="title",
                            max_length=70,
                            required=True,
                        ),
                    ),
                    (
                        "section_content",
                        wagtail.blocks.RichTextBlock(
                            help_text="A brief piece of information about the corporation",
                            required=True,
                        ),
                    ),
                    (
                        "subheading",
                        wagtail.blocks.CharBlock(
                            default="Enhancing co-operation between Earth observation data providers and Governments.",
                            form_classname="subtitle",
                            max_length=100,
                            required=False,
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="homepageaboutsection",
            name="video_caption",
            field=models.CharField(
                blank=True,
                default="Land Degradation Neutrality Initiative",
                max_length=125,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="homepageaboutsection",
            name="video_link",
            field=models.URLField(
                blank=True,
                help_text="Please provide a YouTube embed link",
                null=True,
                unique=True,
            ),
        ),
    ]
