# Generated by Django 4.2.2 on 2023-07-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0030_alter_homepageaboutsection_body_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepageaboutsection",
            name="video_caption",
        ),
        migrations.RemoveField(
            model_name="homepageaboutsection",
            name="video_link",
        ),
        migrations.AddField(
            model_name="homepage",
            name="video_caption",
            field=models.CharField(
                blank=True,
                default="Land Degradation Neutrality Initiative",
                max_length=125,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="video_link",
            field=models.URLField(
                blank=True,
                help_text="Please provide a YouTube embed link",
                null=True,
                unique=True,
            ),
        ),
    ]
