# Generated by Django 4.2.2 on 2023-07-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0031_remove_homepageaboutsection_video_caption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="video_caption",
            field=models.TextField(
                blank=True,
                default="Land Degradation Neutrality Initiative",
                max_length=125,
                null=True,
            ),
        ),
    ]
