# Generated by Django 4.2.2 on 2023-07-05 07:36

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0032_alter_homepage_video_caption"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepageaboutsection",
            name="body",
        ),
        migrations.AddField(
            model_name="homepageaboutsection",
            name="about_section_content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "content",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "caption",
                                                wagtail.blocks.CharBlock(
                                                    required=False
                                                ),
                                            ),
                                            (
                                                "image",
                                                wagtail.images.blocks.ImageChooserBlock(
                                                    required=True
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        default="GEO-LDN FLAGSHIP",
                                        max_length=70,
                                        required=True,
                                    ),
                                ),
                                (
                                    "section_content",
                                    wagtail.blocks.RichTextBlock(
                                        help_text="A brief piece of information about the corporation",
                                        required=True,
                                    ),
                                ),
                                (
                                    "subheading",
                                    wagtail.blocks.CharBlock(
                                        default="Enhancing co-operation between Earth observation data providers and Governments.",
                                        max_length=100,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.CreateModel(
            name="HomePageKeyFocusArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "key_focus_areas",
                    wagtail.fields.StreamField(
                        [
                            (
                                "content",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "icon",
                                            wagtail.blocks.CharBlock(
                                                max_length=70, required=True
                                            ),
                                        ),
                                        (
                                            "title",
                                            wagtail.blocks.CharBlock(
                                                help_text="Key focus area title (not more than 150 words)",
                                                max_length=100,
                                                required=True,
                                            ),
                                        ),
                                        (
                                            "content",
                                            wagtail.blocks.BlockQuoteBlock(
                                                default="Key focus area content (not more than 250 words)",
                                                max_length=255,
                                                required=True,
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        use_json_field=True,
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="key_focus_area_section",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
