# Generated by Django 4.2.2 on 2023-07-05 07:43

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0033_remove_homepageaboutsection_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagekeyfocusarea",
            name="key_focus_areas",
            field=wagtail.fields.StreamField(
                [
                    (
                        "content",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "icon",
                                    wagtail.blocks.CharBlock(
                                        max_length=70, required=True
                                    ),
                                ),
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Key focus area title (not more than 150 words)",
                                        max_length=100,
                                        required=True,
                                    ),
                                ),
                                (
                                    "content",
                                    wagtail.blocks.BlockQuoteBlock(
                                        help_text="Key focus area content (not more than 250 words)",
                                        max_length=255,
                                        required=True,
                                    ),
                                ),
                                (
                                    "related_link",
                                    wagtail.blocks.URLBlock(
                                        help_text="Which page to redirect to",
                                        required=True,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
