# Generated by Django 4.2.2 on 2023-07-05 07:53

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0035_alter_homepagekeyfocusarea_key_focus_areas"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepageaboutsection",
            name="action_button",
            field=wagtail.fields.StreamField(
                [
                    (
                        "call_to_action",
                        wagtail.blocks.StructBlock(
                            [
                                ("link", wagtail.blocks.URLBlock(required=True)),
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        max_length=50, required=True
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="homepagecarousel",
            name="action_button",
            field=wagtail.fields.StreamField(
                [
                    (
                        "call_to_action",
                        wagtail.blocks.StructBlock(
                            [
                                ("link", wagtail.blocks.URLBlock(required=True)),
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        max_length=50, required=True
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
