# Generated by Django 4.2.2 on 2023-07-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0036_homepageaboutsection_action_button_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepagecarousel",
            name="action_button",
        ),
        migrations.AddField(
            model_name="homepagecarousel",
            name="link",
            field=models.URLField(
                default="http://localhost:5000",
                help_text="Please provide a YouTube embed link",
                unique=False,
            ),
        ),
        migrations.AddField(
            model_name="homepagecarousel",
            name="text",
            field=models.CharField(default="Read More", max_length=50),
        ),
    ]
