# Generated by Django 4.2.2 on 2023-07-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0037_remove_homepagecarousel_action_button_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepagecarousel",
            name="link",
            field=models.URLField(
                default="http://localhost:5000",
                help_text="Please provide a YouTube embed link",
            ),
        ),
    ]
