# Generated by Django 4.2.2 on 2023-07-05 09:32

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("home", "0038_alter_homepagecarousel_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepageaboutsection",
            name="about_section_content",
        ),
        migrations.RemoveField(
            model_name="homepageaboutsection",
            name="action_button",
        ),
        migrations.AddField(
            model_name="homepageaboutsection",
            name="action_link",
            field=models.URLField(
                default="http://localhost:5000",
                help_text="Please provide a YouTube embed link",
            ),
        ),
        migrations.AddField(
            model_name="homepageaboutsection",
            name="action_text",
            field=models.CharField(default="Read More", max_length=50),
        ),
        migrations.AddField(
            model_name="homepageaboutsection",
            name="section_content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "content",
                        wagtail.blocks.RichTextBlock(
                            help_text="A brief piece of information about the corporation",
                            required=False,
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="homepageaboutsection",
            name="section_heading",
            field=models.CharField(default="GEO-LDN FLAGSHIP", max_length=100),
        ),
        migrations.AddField(
            model_name="homepageaboutsection",
            name="section_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepageaboutsection",
            name="section_image_caption",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="homepageaboutsection",
            name="section_subheading",
            field=models.CharField(
                blank=True,
                default="Enhancing co-operation between Earth observation data providers and Governments.",
                max_length=150,
            ),
        ),
    ]
