# Generated by Django 4.2.2 on 2023-07-05 09:38

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0039_remove_homepageaboutsection_about_section_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepagekeyfocusarea",
            name="key_focus_areas",
        ),
        migrations.AddField(
            model_name="homepagekeyfocusarea",
            name="focus_content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "content",
                        wagtail.blocks.RichTextBlock(
                            help_text="A brief piece of information about the corporation",
                            required=False,
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="homepagekeyfocusarea",
            name="focus_heading",
            field=models.CharField(
                default="GEO-LDN FLAGSHIP",
                help_text="Key focus area content (not more than 250 words)",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="homepagekeyfocusarea",
            name="focus_icon",
            field=models.CharField(
                default="ri-bubble-chart-line", max_length=70, null=True
            ),
        ),
        migrations.AddField(
            model_name="homepagekeyfocusarea",
            name="focus_link",
            field=models.URLField(
                default="http://localhost:5000",
                help_text="Which page to redirect to",
                null=True,
            ),
        ),
    ]
