# Generated by Django 4.2.2 on 2023-07-05 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0040_remove_homepagekeyfocusarea_key_focus_areas_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepageaboutsection",
            name="section_image_caption",
        ),
    ]
